name: Geo Database

on:
  schedule:
    - cron: "00 19 * * *" # 02:00 GMT+7
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/.github/workflows/main.yml"
      - "**/.github/workflows/delete.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set variables
        run: |
          echo "BUILDTIME=$(TZ=Asia/Jakarta date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@v3
      - name: Update GeoData
        working-directory: ./config
        run : |
          rm -fr Country.mmdb
          rm -fr GeoIP.dat
          rm -fr GeoSite.dat
          echo "Downloading Country.mmdb ..."
          wget https://github.com/sahlandaila/meta-rules-dat/releases/download/latest/country.mmdb -O Country.mmdb
          echo "Downloading GeoIp.dat ..."
          wget https://github.com/sahlandaila/meta-rules-dat/releases/download/latest/geoip.dat -O GeoIP.dat
          echo "Downloading GeoSite.dat ..."
          wget https://github.com/sahlandaila/meta-rules-dat/releases/download/latest/geosite.dat -O GeoSite.dat
          chmod +x Country.mmdb
          chmod +x GeoIP.dat
          chmod +x GeoSite.dat

          chmod +x ./config/config-wrt.yaml
          
          chmod +x ./proxy_provider/pp-browsing.yaml
          chmod +x ./proxy_provider/pp-direct.yaml
          chmod +x ./proxy_provider/pp-gaming.yaml
          chmod +x ./proxy_provider/pp-indo.yaml
          
          chmod +x ./rule_provider/rp-direct.yaml
          chmod +x ./rule_provider/rp-indo.yaml
          chmod +x ./rule_provider/rp-reject.yaml
          chmod +x ./rule_provider/rp-umum.yaml

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🎉 Sync: ${{ env.BUILDTIME }}"
    
      - name: Move and zip files
        run: |
          tar -czvf Backup-OpenClash-$(TZ=Asia/Jakarta date +'%Y-%m-%d-%H-%M-%S').tar.gz -C ./config .

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          deleteOnlyFromDrafts: false

      - name: Create and Upload Release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Config Clash Meta - ${{ env.BUILDTIME }}
          tag: latest
          file_glob: true
          overwrite: true
          file: ./*.tar.gz
          body: |
            ### Update Config ClashMeta - RTA SERVER
            Build date: ${{ env.BUILDTIME }}
            See [here](https://github.com/sahlandaila/meta-rules-dat) for more detail feature and other information.
            - Auto Update GeoIP
            - Auto Update GeoSite

      # - name: Send Telegram
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_CHAT_ID }}
      #     token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     format: markdown
      #     document: ./Backup-OpenClash-$(date +'%Y-%m-%d-%H-%M-%S').tar.gz
      #     message: |
      #       ### Update Config ClashMeta - RTA SERVER
      #       Build date: ${{ env.BUILDTIME }}
      #       See [here](https://github.com/rtaserver/meta-rules-dat) for more detail feature and other information.
      #       - Auto Update GeoIP
      #       - Auto Update GeoSite
    
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: 0
          keep_minimum_runs: 1
